/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.Arrays;

public class Bitmap {
    public static void main(String[] args) {
        readImg();
    }
  public static void readImg(){
      BufferedImage image=null;
      File imgFile=null;
      int width=2;
      int height=2;
      try{
  imgFile=new File("mario.bmp");
  image=new BufferedImage(width,height,BufferedImage.TYPE_INT_ARGB);
  image= ImageIO.read(imgFile);
   byte[]  pixels= (byte[]) image.getRaster().getDataElements(0,0,image.getWidth(),image.getHeight(),null);

           System.out.println(pixels);



      }catch (IOException ex){
          System.out.println("hi");
      }

  }
}
