/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.Arrays;

public class Bitmap {
    //Instance Variable
    BufferedImage pixelData;

    // === constructor ===
    public Bitmap() {

    }

    public Bitmap(String fileName) throws IOException {
        File f =new File(fileName);
        this.pixelData = ImageIO.read(f);
        System.out.println("Reading complete.");

    }

    // === instance methods ===

    // instance that writes the new image to the desired file
    public void write(String fileNameToWrite) throws IOException {
        File f = new File(fileNameToWrite);
        ImageIO.write(this.pixelData,"bmp",f);
        System.out.println("Completed Writing");

    }


//    public static void readImg() throws IOException {
//      BufferedImage image=null;
//      File imgFile=null;
//      int width=2;
//      int height=2;
//
//  imgFile=new File("mario.bmp");
//  image=new BufferedImage(width,height,BufferedImage.TYPE_INT_ARGB);
//  image= ImageIO.read(imgFile);
//   byte[]  pixels= (byte[]) image.getRaster().getDataElements(0,0,image.getWidth(),image.getHeight(),null);
//
//           System.out.println(pixels);
//
//  }
}
